imports:
    - { resource: config_dev.yml }
    - { resource: database_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

swiftmailer:
    disable_delivery: true
