doctrine:
    dbal:
        driver: pdo_sqlite
        memory: false
        path: %kernel.root_dir%/sqlite-dev.db
        charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
