doctrine:
    default_connection: default
    connections:
        default:
            driver:   pdo_sqlite
            memory:   true
    dbal:
        driver: pdo_sqlite
        path: %kernel.root_dir%/sqlite-test.db
        charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
